### ISSUE TITLE
passthrough: Use of $ as currency symbol

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo-goldmark-extensions#3]
This works on GitHub, GitLab, and in VS Code markdown previews:

```
The price is $10.00, but members get a discount. The final price is $p' = p(1-d)$.
```

But we render this to:

```html
<p>The price is $10.00, but members get a discount. The final price is $p&rsquo; = p(1-d)$.</p>
```

I can work around this by disabling the single `$` inline delimiter, and use the parentheses delimiters instead:

```toml
[markup.goldmark.extensions.passthrough.delimiters]
block = [['$$', '$$'], ['\[', '\]']]
inline = [['\(', '\)']]
```

markdown

```text
The price is $10.00, but members get a discount. The final price is \(p' = p(1-d)\).
```

Note that this parentheses example fails with KaTeX but works fine with MathJax... another reason to change our defaults as described here: https://github.com/gohugoio/hugo/pull/11866#issuecomment-1904494836

---

FYI

GitLab renders with KaTeX, while GitHub renders with MathJax. MathJax v2.7 was a lot slower than KaTeX, but v3 is fast. A compelling comparison: https://www.intmath.com/cg5/katex-mathjax-comparison.php
